# =============================================================================
# 50 - Make the walkthrough "just work":
#       * PowerShell profile with `dfir-aio` (launch container) + helper funcs
#       * Desktop shortcuts (lab folder, WSL terminal, README)
#       * A rich Desktop README (HTML) tying Windows-native + container together
# =============================================================================
$ErrorActionPreference = 'Stop'

# --------------------------- PowerShell profile -----------------------------
# AllUsersAllHosts so every shell (incl. the Analyst account) gets the helpers.
$profilePath = $PROFILE.AllUsersAllHosts
New-Item -ItemType Directory -Force -Path (Split-Path $profilePath) | Out-Null

$profileBody = @'
# ---- DFIR Lab helpers (auto-generated by dfir-lab-vm) ----
function dfir-aio {
    <#
      Launch the offline dfir-aio:v2 Linux toolbox in WSL2, mounting a folder as /data.
      Usage:
        dfir-aio                  # mounts the current directory as /data, opens the shell
        dfir-aio C:\dfir\lab\module-01-prefetch-pecmd\data
        dfir-aio . PECmd -d /data --csv /data   # run one tool non-interactively
    #>
    param(
        [string]$DataDir = (Get-Location).Path,
        [Parameter(ValueFromRemainingArguments=$true)] $Cmd
    )
    $full = (Resolve-Path $DataDir).Path
    $wsl  = (wsl -d Ubuntu -- wslpath "$full").Trim()
    $tail = if ($Cmd) { ($Cmd -join ' ') } else { '' }
    # Ensure docker is up, then run the container.
    wsl -d Ubuntu -u root -- bash -lic "service docker start >/dev/null 2>&1 || (pgrep dockerd >/dev/null 2>&1 || (dockerd >/var/log/dockerd.log 2>&1 &)); sleep 2" | Out-Null
    wsl -d Ubuntu -- bash -lic "docker run -it --rm -v '$wsl':/data dfir-aio:v2 $tail"
}

function dfir-lab   { Set-Location 'C:\dfir\lab' ; Get-ChildItem -Directory | Select-Object Name }
function dfir-wsl   { wsl -d Ubuntu }
Set-Alias dfir dfir-lab

Write-Host "DFIR lab ready. Try:  dfir-lab   |   dfir-aio   |   PECmd --help" -ForegroundColor Cyan
# ---- end DFIR Lab helpers ----
'@
Set-Content -Path $profilePath -Value $profileBody -Encoding UTF8
Write-Host "[shortcuts] Wrote profile: $profilePath"

# ------------------------------ Desktop README ------------------------------
$publicDesktop = Join-Path $env:PUBLIC 'Desktop'
New-Item -ItemType Directory -Force -Path $publicDesktop | Out-Null
$readmeHtml = Join-Path $publicDesktop 'DFIR-LAB-README.html'

$html = @'
<!doctype html><html><head><meta charset="utf-8"><title>DFIR Lab VM</title>
<style>
 body{font-family:Segoe UI,Arial,sans-serif;max-width:880px;margin:30px auto;padding:0 20px;color:#1b1b1b;line-height:1.5}
 h1{color:#6a1b9a} h2{color:#4527a0;border-bottom:2px solid #eee;padding-top:14px}
 code,pre{background:#f4f4f8;border:1px solid #e0e0ec;border-radius:4px}
 code{padding:1px 5px} pre{padding:10px;overflow:auto}
 table{border-collapse:collapse;width:100%} td,th{border:1px solid #ddd;padding:6px 8px;text-align:left}
 .tip{background:#ede7f6;border-left:4px solid #6a1b9a;padding:8px 12px;margin:12px 0}
</style></head><body>
<h1>DFIR Training Lab VM</h1>
<p>This VM was auto-built by <b>zepedara/dfir-lab-vm</b> (Packer). It has everything
you need to run the <b>dfir-training-lab</b> walkthrough natively, using <b>both</b>
Windows-native DFIR tools <b>and</b> the Linux <code>dfir-aio:v2</code> container in WSL2.</p>

<div class="tip"><b>Login:</b> Analyst / dfir &nbsp;|&nbsp; <b>Lab:</b> C:\dfir\lab &nbsp;|&nbsp; <b>Tools:</b> C:\dfir\tools</div>

<h2>Two ways to run every exercise</h2>
<table>
<tr><th>Native (Windows)</th><th>Container (WSL2 / Linux)</th></tr>
<tr><td>Eric Zimmerman tools, Chainsaw, Hayabusa, Sysinternals are on your PATH.<br>
Open <b>PowerShell</b> and run them directly:<br>
<pre>cd C:\dfir\lab\module-01-prefetch-pecmd\data
PECmd -d . --csv . --csvf prefetch.csv</pre></td>
<td>The whole offline toolbox in one container. From PowerShell:<br>
<pre>cd C:\dfir\lab\module-01-prefetch-pecmd\data
dfir-aio          # opens the toolbox, this folder is /data
# or run one tool:
dfir-aio . PECmd -d /data --csv /data</pre></td></tr>
</table>

<h2>Handy commands (already on your profile)</h2>
<table>
<tr><th>Command</th><th>What it does</th></tr>
<tr><td><code>dfir-lab</code></td><td>cd to C:\dfir\lab and list the modules</td></tr>
<tr><td><code>dfir-aio</code></td><td>launch the dfir-aio:v2 container in WSL, mounting the current folder as /data</td></tr>
<tr><td><code>dfir-wsl</code></td><td>drop into the Ubuntu (WSL2) shell</td></tr>
</table>

<h2>The lab (work modules 1 -> 10)</h2>
<ol>
<li>Prefetch (PECmd) - what ran, when, how often</li>
<li>ShimCache (AppCompatCacheParser) - what the OS saw</li>
<li>Amcache (AmcacheParser) - inventory + SHA1 attribution</li>
<li>Scaling the hunt (AppCompatProcessor)</li>
<li>Event logs (EvtxECmd)</li>
<li>Sigma hunting (Chainsaw + Hayabusa)</li>
<li>Identity &amp; credential theft (event-log analysis)</li>
<li>Lateral movement</li>
<li>PowerShell tradecraft</li>
<li>Sysmon + WEF</li>
</ol>
<p>Each module folder has a <code>README.md</code> with theory, the tool, guided
exercises, and what to find. Start at module 01 and follow the order.</p>

<div class="tip">Tip: tool output CSVs open nicely in <b>Timeline Explorer</b> (an EZ tool) or Excel.
The container and the native tools read the <i>same</i> files - use whichever you prefer per step.</div>

<p style="color:#888;font-size:12px">Offline by design once built. Eval Windows licence applies. Educational use.</p>
</body></html>
'@
Set-Content -Path $readmeHtml -Value $html -Encoding UTF8
Write-Host "[shortcuts] Wrote desktop README: $readmeHtml"

# ------------------------------ Shortcuts -----------------------------------
function New-Shortcut($lnk, $target, $arguments, $workdir) {
    $ws = New-Object -ComObject WScript.Shell
    $s = $ws.CreateShortcut($lnk)
    $s.TargetPath = $target
    if ($arguments) { $s.Arguments = $arguments }
    if ($workdir)   { $s.WorkingDirectory = $workdir }
    $s.Save()
}
try {
    New-Shortcut (Join-Path $publicDesktop 'DFIR Lab folder.lnk') 'C:\dfir\lab' $null 'C:\dfir\lab'
    New-Shortcut (Join-Path $publicDesktop 'DFIR WSL toolbox.lnk') "$env:WINDIR\System32\wsl.exe" '-d Ubuntu' 'C:\dfir\lab'
    New-Shortcut (Join-Path $publicDesktop 'DFIR PowerShell.lnk') "$env:WINDIR\System32\WindowsPowerShell\v1.0\powershell.exe" '-NoExit -Command "dfir-lab"' 'C:\dfir\lab'
    Write-Host '[shortcuts] Desktop shortcuts created.'
} catch { Write-Warning "[shortcuts] shortcut creation issue: $($_.Exception.Message)" }

exit 0
